name: Ruby Gem

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.0' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: sudo apt-get install libusb-1.0.0-dev libffi-dev
    - run: bundle
    - run: gem install require
    - run: gem install hex_string
    - run: gem install hexdump
    - run: gem install colorize
    - run: gem install optparse
    - run: gem install libusb
    - run: gem install bindata
    - run: gem install crc32
    - run: gem install rc6
    - run: gem install thread
    - run: gem install inifile
    - run: gem install fileutils
    - run: gem install stringio
    
    - run: chmod +x ./felix
    - run: ./felix --help 
